----
- name: create mysql database
  mysql_db:
    name: {{ mysql_database }}
    state: present
    login_user: "root"
    login_password: "{{ mysql_root_connect_root_password }}"

- name: create mysql user
  mysql_user:
    name: {{ mysql_user }}
    host: {{ mysql_host_list }} 
    password: {{ mysql_password }}
    priv: {{ mysql_database }}.*:ALL,GRANT
    login_user: "root"
    login_password: "{{ mysql_root_connect_root_password }}"
    state: present
